name: Bump Version and Create Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump type: patch, minor, major"
        required: false
        default: "patch"

jobs:
  bump-and-release:
    runs-on: macos-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to push tags

      - name: 🌐 Set up Node.js (for standard-version)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🐾 Install standard-version
        run: npm install -g standard-version

      - name: 📆 Bump version using conventional commits
        run: |
          standard-version --release-as ${{ github.event.inputs.bump }}
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: 📆 Generate CHANGELOG.md from conventional commits
        run: echo "CHANGELOG updated as part of version bump"

      - name: 🔢 Update Info.plist version
        run: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION" Packages/PressyBar.app/Contents/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $VERSION" Packages/PressyBar.app/Contents/Info.plist

      - name: 📍 Commit version bump and changelog
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "chore(release): v$VERSION"
          git tag v$VERSION
          git push origin HEAD
          git push origin v$VERSION

      - name: 🚀 Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
